/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.7.0
 *
 * Project: 'viewfinder.debug+HP' 
 * Target:  'debug+HP' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "alif.h"

/* AlifSemiconductor::BSP:External peripherals:CAMERA Sensor MT9M114@1.3.0 */
#define RTE_Drivers_CAMERA_SENSOR_MT9M114            /* Driver CAMERA Sensor */
/* AlifSemiconductor::BSP:External peripherals:ILI9806E LCD panel@1.3.0 */
#define RTE_Drivers_MIPI_DSI_ILI9806E_PANEL    /* Driver ILI9806E LCD panel*/
/* AlifSemiconductor::CMSIS Driver:I2C@1.3.0 */
#define RTE_Drivers_I2C              /* Driver I2C */
/* AlifSemiconductor::CMSIS Driver:USART@1.3.0 */
#define RTE_Drivers_USART               /* Driver UART  */
/* AlifSemiconductor::Device:SOC Peripherals:CDC@1.3.0 */
#define RTE_Drivers_CDC200                 /* Driver CDC200*/
/* AlifSemiconductor::Device:SOC Peripherals:CPI@1.3.0 */
#define RTE_Drivers_CPI              /* Driver CAMERA Controller */
/* AlifSemiconductor::Device:SOC Peripherals:GPIO@1.3.0 */
#define RTE_Drivers_GPIO              /* Driver GPIO */
/* AlifSemiconductor::Device:SOC Peripherals:MIPI CSI2@1.3.0 */
#define RTE_Drivers_MIPI_CSI2              /* Driver MIPI CSI2 */
/* AlifSemiconductor::Device:SOC Peripherals:MIPI DSI CSI2 DPHY@1.3.0 */
#define RTE_Drivers_MIPI_DSI_CSI2_DPHY   /* Driver DPHY */
/* AlifSemiconductor::Device:SOC Peripherals:MIPI DSI@1.3.0 */
#define RTE_Drivers_MIPI_DSI               /* Driver MIPI DSI */
/* AlifSemiconductor::Device:SOC Peripherals:PINCONF@1.3.0 */
#define RTE_Drivers_LL_PINCONF              /* Driver PinPAD and PinMux */
/* AlifSemiconductor::Graphics:Acceleration:Dave2d@1.0.0 */
/*! \brief enable Dave2D acceleration */
#define AIPL_DAVE2D_ACCELERATION
/* AlifSemiconductor::Graphics:Acceleration:Helium@1.0.1 */
/*! \brief enable Helium */
#define AIPL_HELIUM_ACCELERATION


#endif /* RTE_COMPONENTS_H */
